services:
  # Traefik reverse proxy
  traefik:
    image: traefik:v3.1
    container_name: eventsamo-traefik
    restart: unless-stopped
    command:
      - "--log.level=INFO"
      - "--accesslog=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=traefik-network"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      # HTTP to HTTPS redirect
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      # Let's Encrypt configuration
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.email=arminramusovic11@gmail.com"  # Change this!
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      # Optional: Enable Traefik dashboard (remove in production)
#      - "--api.dashboard=true"
#      - "--api.insecure=true"
    ports:
      - "80:80"
      - "443:443"
#      - "8080:8080"  # Traefik dashboard (remove in production)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik_letsencrypt:/letsencrypt
    networks:
      - traefik-network

  app:
    image: myapp:prod
    container_name: eventsamo-backend
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:mysql://eventsamo-mysql:3306/eventsdb
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: "${MAIL_PASSWORD}"
    expose:
      - "8080"  # Internal port for Traefik
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - app-network
      - traefik-network  # Connect to Traefik network
    volumes:
      - app-logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s
    labels:
      # Enable Traefik for this service
      - "traefik.enable=true"
      # CRITICAL: Use the full network name with project prefix
      - "traefik.docker.network=events-amo-backend_traefik-network"
      - "traefik.http.routers.eventsamo-app.rule=Host(`api.arminramusovic.com`)"
      - "traefik.http.routers.eventsamo-app.entrypoints=websecure"
      - "traefik.http.routers.eventsamo-app.tls.certresolver=letsencrypt"
      # HTTP router (redirect to HTTPS)
      - "traefik.http.routers.eventsamo-app-http.rule=Host(`api.arminramusovic.com`)"
      - "traefik.http.routers.eventsamo-app-http.entrypoints=web"
      - "traefik.http.routers.eventsamo-app-http.middlewares=redirect-to-https"
      # Redirect middleware
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true"
      # Service configuration - specify the port
      - "traefik.http.services.eventsamo-app.loadbalancer.server.port=8080"
      # Optional: Add middleware for rate limiting, auth, etc.
      # - "traefik.http.middlewares.eventsamo-ratelimit.ratelimit.average=100"
      # - "traefik.http.routers.eventsamo-app.middlewares=eventsamo-ratelimit"

  db:
    image: mysql:8.0
    container_name: eventsamo-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: eventsdb
      MYSQL_USER: ${SPRING_DATASOURCE_USERNAME}
      MYSQL_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "${SPRING_DATASOURCE_USERNAME}", "-p${SPRING_DATASOURCE_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    expose:
      - "3306"  # Only accessible internally
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_config:/etc/mysql/conf.d
    networks:
      - app-network  # Only connected to app network
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:
    driver: local
  mysql_config:
    driver: local
  app-logs:
    driver: local
  traefik_letsencrypt:  # New volume for Let's Encrypt certificates
    driver: local

networks:
  app-network:
    driver: bridge
  traefik-network:  # New network for Traefik
    driver: bridge
    external: false
